# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVoA7bO9tDtuuJyDYU7nYVJ3J1SCoCbZ
"""

import os
import time
from pathlib import Path

import pandas as pd
import requests
from dotenv import load_dotenv

load_dotenv()

# Paths
INPUT_CSV = Path("/content/drive/MyDrive/satellite-property-valuation/data/processed/train_with_images.csv")
OUTPUT_DIR = Path("/content/drive/MyDrive/satellite-property-valuation/data/images")

# Mapbox configuration
MAPBOX_KEY = os.getenv("MAPBOX_TOKEN")
MAP_STYLE = "satellite-v9"
ZOOM = 18
IMG_DIM = "256x256"

# Rate limiting & safety
SLEEP_TIME = 0.12
DOWNLOAD_LIMIT = 6000


if not MAPBOX_KEY:
    raise EnvironmentError(
        "MAPBOX_TOKEN is missing. "
        "Add it to your environment or .env file."
    )


def generate_static_map_url(latitude, longitude):
    """
    Construct a Mapbox Static API URL for satellite imagery.
    """
    return (
        "https://api.mapbox.com/styles/v1/mapbox/"
        f"{MAP_STYLE}/static/"
        f"{longitude},{latitude},{ZOOM}/{IMG_DIM}"
        f"?access_token={MAPBOX_KEY}"
    )


def save_image_from_url(url, filepath):
    """
    Fetch image from URL and persist to disk.
    """
    try:
        resp = requests.get(url, timeout=12)
        if resp.status_code == 200:
            with open(filepath, "wb") as f:
                f.write(resp.content)
            return True
        else:
            print(f"HTTP {resp.status_code} for {filepath.name}")
            return False

    except requests.RequestException as err:
        print(f"Network error: {err}")
        return False


def run_image_collection():
    print("🚀 Initializing satellite image fetcher")

    print(f"→ Reading input CSV: {INPUT_CSV}")
    print(f"→ Saving images to: {OUTPUT_DIR}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    data = pd.read_csv(INPUT_CSV)
    print(f"Records loaded: {len(data)}")

    expected_cols = {"id", "lat", "long"}
    if not expected_cols.issubset(data.columns):
        raise ValueError(f"CSV must contain columns: {expected_cols}")

    geo_df = data[list(expected_cols)].dropna().copy()

    initial_count = len(geo_df)
    geo_df = geo_df.drop_duplicates(subset="id").reset_index(drop=True)
    print(f"Duplicates removed: {initial_count - len(geo_df)}")

    print("Latitude bounds :", geo_df["lat"].min(), "→", geo_df["lat"].max())
    print("Longitude bounds:", geo_df["long"].min(), "→", geo_df["long"].max())

    fetched = 0
    print("📥 Starting downloads...")

    for _, rec in geo_df.iterrows():

        if fetched >= DOWNLOAD_LIMIT:
            print("⚠️ Download cap reached")
            break

        prop_id = float(rec["id"])
        output_path = OUTPUT_DIR / f"{prop_id}.png"

        if output_path.exists():
            continue

        map_url = generate_static_map_url(
            latitude=rec["lat"],
            longitude=rec["long"]
        )

        if save_image_from_url(map_url, output_path):
            fetched += 1
        else:
            print(f"Failed image for property {prop_id}")

        time.sleep(SLEEP_TIME)

    print(f"✅ Finished. Images downloaded: {fetched}")


if __name__ == "__main__":
    run_image_collection()